#!/bin/bash
php Task.php "First Message."
php Task.php "Ten Message...................."
php Task.php "Third Message..."
php Task.php "Forth Message...."
php Task.php "Fifth Message....."
php Task.php "First Message."
php Task.php "First Message."
php Task.php "Eighth Message........"
php Task.php "First Message."
php Task.php "First Message."
